[package]
name = "rust"
version = "0.1.0"
authors = ["Nick <niiick@live.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floating-duration = "*"